// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Access related settings for IAP protected apps.
public struct AccessSettings: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. GCIP claims and endpoint configurations for 3p identity
  /// providers.
  public var gcipSettings: GcipSettings? = nil

  /// Optional. Configuration to allow cross-origin requests via IAP.
  public var corsSettings: CorsSettings? = nil

  /// Optional. Settings to configure IAP's OAuth behavior.
  public var oauthSettings: OAuthSettings? = nil

  /// Optional. Settings to configure reauthentication policies in IAP.
  public var reauthSettings: ReauthSettings? = nil

  /// Optional. Settings to configure and enable allowed domains.
  public var allowedDomainsSettings: AllowedDomainsSettings? = nil

  /// Optional. Settings to configure the workforce identity federation,
  /// including workforce pools and OAuth 2.0 settings.
  public var workforceIdentitySettings: WorkforceIdentitySettings? = nil

  /// Optional. Identity sources that IAP can use to authenticate the end user.
  /// Only one identity source can be configured.
  public var identitySources: [AccessSettings.IdentitySource] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AccessSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AccessSettings().with { $0.gcipSettings = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gcipSettings = CodingKeys(stringValue: "gcipSettings")
    static let corsSettings = CodingKeys(stringValue: "corsSettings")
    static let oauthSettings = CodingKeys(stringValue: "oauthSettings")
    static let reauthSettings = CodingKeys(stringValue: "reauthSettings")
    static let allowedDomainsSettings = CodingKeys(stringValue: "allowedDomainsSettings")
    static let workforceIdentitySettings = CodingKeys(stringValue: "workforceIdentitySettings")
    static let identitySources = CodingKeys(stringValue: "identitySources")

    static let _knownKeys: Set<Swift.String> = [
      "gcipSettings",
      "corsSettings",
      "oauthSettings",
      "reauthSettings",
      "allowedDomainsSettings",
      "workforceIdentitySettings",
      "identitySources",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.gcipSettings = try container.decodeIfPresent(GcipSettings.self, forKey: .gcipSettings)
    self.corsSettings = try container.decodeIfPresent(CorsSettings.self, forKey: .corsSettings)
    self.oauthSettings = try container.decodeIfPresent(OAuthSettings.self, forKey: .oauthSettings)
    self.reauthSettings = try container.decodeIfPresent(
      ReauthSettings.self, forKey: .reauthSettings)
    self.allowedDomainsSettings = try container.decodeIfPresent(
      AllowedDomainsSettings.self, forKey: .allowedDomainsSettings)
    self.workforceIdentitySettings = try container.decodeIfPresent(
      WorkforceIdentitySettings.self, forKey: .workforceIdentitySettings)
    if let value = try container.decodeIfPresent(
      [AccessSettings.IdentitySource].self, forKey: .identitySources)
    {
      self.identitySources = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.gcipSettings, forKey: .gcipSettings)
    try container.encodeIfPresent(self.corsSettings, forKey: .corsSettings)
    try container.encodeIfPresent(self.oauthSettings, forKey: .oauthSettings)
    try container.encodeIfPresent(self.reauthSettings, forKey: .reauthSettings)
    try container.encodeIfPresent(self.allowedDomainsSettings, forKey: .allowedDomainsSettings)
    try container.encodeIfPresent(
      self.workforceIdentitySettings, forKey: .workforceIdentitySettings)
    try container.encode(self.identitySources, forKey: .identitySources)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Types of identity source supported by IAP.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum IdentitySource: Codable, Equatable, Hashable, Sendable {
    /// IdentitySource Unspecified.
    /// When selected, IAP relies on which identity settings are fully configured
    /// to redirect the traffic to. The precedence order is
    /// WorkforceIdentitySettings > GcipSettings. If none is set, default to use
    /// Google identity.
    case unspecified
    /// Use external identities set up on Google Cloud Workforce Identity
    /// Federation.
    case workforceIdentityFederation
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .workforceIdentityFederation: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "IDENTITY_SOURCE_UNSPECIFIED"
      case .workforceIdentityFederation: return "WORKFORCE_IDENTITY_FEDERATION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:IdentitySource/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "IDENTITY_SOURCE_UNSPECIFIED": self = .unspecified
      case "WORKFORCE_IDENTITY_FEDERATION": self = .workforceIdentityFederation
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:IdentitySource/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 3: self = .workforceIdentityFederation
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("IDENTITY_SOURCE_UNSPECIFIED")
      case .workforceIdentityFederation:
        return try container.encode("WORKFORCE_IDENTITY_FEDERATION")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.iap.v1.AccessSettings"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
