// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Wrapper over application specific settings for IAP.
public struct ApplicationSettings: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Settings to configure IAP's behavior for a service mesh.
  public var csmSettings: CsmSettings? = nil

  /// Optional. Customization for Access Denied page.
  public var accessDeniedPageSettings: AccessDeniedPageSettings? = nil

  /// The Domain value to set for cookies generated by IAP. This value is not
  /// validated by the API, but will be ignored at runtime if invalid.
  public var cookieDomain: GoogleWKT.WKTStringValue? = nil

  /// Optional. Settings to configure attribute propagation.
  public var attributePropagationSettings: AttributePropagationSettings? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ApplicationSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ApplicationSettings().with { $0.csmSettings = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let csmSettings = CodingKeys(stringValue: "csmSettings")
    static let accessDeniedPageSettings = CodingKeys(stringValue: "accessDeniedPageSettings")
    static let cookieDomain = CodingKeys(stringValue: "cookieDomain")
    static let attributePropagationSettings = CodingKeys(
      stringValue: "attributePropagationSettings")

    static let _knownKeys: Set<Swift.String> = [
      "csmSettings",
      "accessDeniedPageSettings",
      "cookieDomain",
      "attributePropagationSettings",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.csmSettings = try container.decodeIfPresent(CsmSettings.self, forKey: .csmSettings)
    self.accessDeniedPageSettings = try container.decodeIfPresent(
      AccessDeniedPageSettings.self, forKey: .accessDeniedPageSettings)
    self.cookieDomain = try container.decodeIfPresent(
      GoogleWKT.WKTStringValue.self, forKey: .cookieDomain)
    self.attributePropagationSettings = try container.decodeIfPresent(
      AttributePropagationSettings.self, forKey: .attributePropagationSettings)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.csmSettings, forKey: .csmSettings)
    try container.encodeIfPresent(self.accessDeniedPageSettings, forKey: .accessDeniedPageSettings)
    try container.encodeIfPresent(self.cookieDomain, forKey: .cookieDomain)
    try container.encodeIfPresent(
      self.attributePropagationSettings, forKey: .attributePropagationSettings)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `ApplicationSettings`: `"type.googleapis.com/google.cloud.iap.v1.ApplicationSettings"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.iap.v1.ApplicationSettings"
  }

  /// Initialize an instance of `ApplicationSettings` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.iap.v1.ApplicationSettings"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ApplicationSettings` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
