// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration for propagating attributes to applications protected
/// by IAP.
public struct AttributePropagationSettings: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Raw string CEL expression. Must return a list of attributes. A
  /// maximum of 45 attributes can be selected. Expressions can select different
  /// attribute types from `attributes`: `attributes.saml_attributes`,
  /// `attributes.iap_attributes`. The following functions are supported:
  ///
  ///  - filter `<list>.filter(<iter_var>, <predicate>)`: Returns a subset of
  ///  `<list>` where `<predicate>` is true for every item.
  ///
  ///  - in `<var> in <list>`: Returns true if `<list>` contains `<var>`.
  ///
  ///  - selectByName `<list>.selectByName(<string>)`: Returns the attribute
  ///  in
  ///  `<list>` with the given `<string>` name, otherwise returns empty.
  ///
  ///  - emitAs `<attribute>.emitAs(<string>)`: Sets the `<attribute>` name
  ///  field to the given `<string>` for propagation in selected output
  ///  credentials.
  ///
  ///  - strict `<attribute>.strict()`: Ignores the `x-goog-iap-attr-` prefix
  ///  for the provided `<attribute>` when propagating with the `HEADER` output
  ///  credential, such as request headers.
  ///
  ///  - append `<target_list>.append(<attribute>)` OR
  ///  `<target_list>.append(<list>)`: Appends the provided `<attribute>` or
  ///  `<list>` to the end of `<target_list>`.
  ///
  /// Example expression: `attributes.saml_attributes.filter(x, x.name in
  /// ['test']).append(attributes.iap_attributes.selectByName('exact').emitAs('custom').strict())`
  public var expression: Swift.String? = nil

  /// Optional. Which output credentials attributes selected by the CEL
  /// expression should be propagated in. All attributes will be fully duplicated
  /// in each selected output credential.
  public var outputCredentials: [AttributePropagationSettings.OutputCredentials] = []

  /// Optional. Whether the provided attribute propagation settings should be
  /// evaluated on user requests. If set to true, attributes returned from the
  /// expression will be propagated in the set output credentials.
  public var enable: Swift.Bool? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AttributePropagationSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AttributePropagationSettings().with { $0.expression = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let expression = CodingKeys(stringValue: "expression")
    static let outputCredentials = CodingKeys(stringValue: "outputCredentials")
    static let enable = CodingKeys(stringValue: "enable")

    static let _knownKeys: Set<Swift.String> = [
      "expression",
      "outputCredentials",
      "enable",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.expression = try container.decodeIfPresent(Swift.String.self, forKey: .expression)
    if let value = try container.decodeIfPresent(
      [AttributePropagationSettings.OutputCredentials].self, forKey: .outputCredentials)
    {
      self.outputCredentials = value
    }
    self.enable = try container.decodeIfPresent(Swift.Bool.self, forKey: .enable)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.expression, forKey: .expression)
    try container.encode(self.outputCredentials, forKey: .outputCredentials)
    try container.encodeIfPresent(self.enable, forKey: .enable)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Supported output credentials for attribute propagation. Each output
  /// credential maps to a "field" in the response. For example, selecting JWT
  /// will propagate all attributes in the IAP JWT, header in the headers, etc.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum OutputCredentials: Codable, Equatable, Hashable, Sendable {
    /// An output credential is required.
    case unspecified
    /// Propagate attributes in the headers with "x-goog-iap-attr-" prefix.
    case header
    /// Propagate attributes in the JWT of the form: `"additional_claims": {
    /// "my_attribute": ["value1", "value2"] }`
    case jwt
    /// Propagate attributes in the RCToken of the form: `"additional_claims": {
    /// "my_attribute": ["value1", "value2"] }`
    case rctoken
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .header: return 1
      case .jwt: return 2
      case .rctoken: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "OUTPUT_CREDENTIALS_UNSPECIFIED"
      case .header: return "HEADER"
      case .jwt: return "JWT"
      case .rctoken: return "RCTOKEN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:OutputCredentials/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "OUTPUT_CREDENTIALS_UNSPECIFIED": self = .unspecified
      case "HEADER": self = .header
      case "JWT": self = .jwt
      case "RCTOKEN": self = .rctoken
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:OutputCredentials/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .header
      case 2: self = .jwt
      case 3: self = .rctoken
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("OUTPUT_CREDENTIALS_UNSPECIFIED")
      case .header: return try container.encode("HEADER")
      case .jwt: return try container.encode("JWT")
      case .rctoken: return try container.encode("RCTOKEN")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `AttributePropagationSettings`: `"type.googleapis.com/google.cloud.iap.v1.AttributePropagationSettings"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.iap.v1.AttributePropagationSettings"
  }

  /// Initialize an instance of `AttributePropagationSettings` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.iap.v1.AttributePropagationSettings"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `AttributePropagationSettings` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
