// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// OAuth brand data.
/// NOTE: Only contains a portion of the data that describes a brand.
public struct Brand: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Identifier of the brand.
  /// NOTE: GCP project number achieves the same brand identification purpose as
  /// only one brand per project can be created.
  public var name: Swift.String = Swift.String()

  /// Support email displayed on the OAuth consent screen.
  public var supportEmail: Swift.String = Swift.String()

  /// Application name displayed on OAuth consent screen.
  public var applicationTitle: Swift.String = Swift.String()

  /// Output only. Whether the brand is only intended for usage inside the
  /// G Suite organization only.
  public var orgInternalOnly: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Brand`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Brand().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let supportEmail = CodingKeys(stringValue: "supportEmail")
    static let applicationTitle = CodingKeys(stringValue: "applicationTitle")
    static let orgInternalOnly = CodingKeys(stringValue: "orgInternalOnly")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "supportEmail",
      "applicationTitle",
      "orgInternalOnly",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .supportEmail) {
      self.supportEmail = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .applicationTitle) {
      self.applicationTitle = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .orgInternalOnly) {
      self.orgInternalOnly = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.supportEmail, forKey: .supportEmail)
    try container.encode(self.applicationTitle, forKey: .applicationTitle)
    try container.encode(self.orgInternalOnly, forKey: .orgInternalOnly)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `Brand`: `"type.googleapis.com/google.cloud.iap.v1.Brand"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.iap.v1.Brand"
  }

  /// Initialize an instance of `Brand` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.iap.v1.Brand"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `Brand` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
