// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Allows customers to configure tenant IDs for a Cloud Identity Platform (GCIP)
/// instance for each application.
public struct GcipSettings: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. GCIP tenant IDs that are linked to the IAP resource. `tenant_ids`
  /// could be a string beginning with a number character to indicate
  /// authenticating with GCIP tenant flow, or in the format of
  /// `_<ProjectNumber>` to indicate authenticating with GCIP agent flow. If
  /// agent flow is used, `tenant_ids` should only contain one single element,
  /// while for tenant flow, `tenant_ids` can contain multiple elements.
  public var tenantIds: [Swift.String] = []

  /// Login page URI associated with the GCIP tenants.
  /// Typically, all resources within the same project share the same login page,
  /// though it could be overridden at the sub resource level.
  public var loginPageUri: GoogleWKT.WKTStringValue? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GcipSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GcipSettings().with { $0.tenantIds = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let tenantIds = CodingKeys(stringValue: "tenantIds")
    static let loginPageUri = CodingKeys(stringValue: "loginPageUri")

    static let _knownKeys: Set<Swift.String> = [
      "tenantIds",
      "loginPageUri",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .tenantIds) {
      self.tenantIds = value
    }
    self.loginPageUri = try container.decodeIfPresent(
      GoogleWKT.WKTStringValue.self, forKey: .loginPageUri)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.tenantIds, forKey: .tenantIds)
    try container.encodeIfPresent(self.loginPageUri, forKey: .loginPageUri)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `GcipSettings`: `"type.googleapis.com/google.cloud.iap.v1.GcipSettings"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.iap.v1.GcipSettings"
  }

  /// Initialize an instance of `GcipSettings` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.iap.v1.GcipSettings"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `GcipSettings` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
