// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration for OAuth login&consent flow behavior as well as for OAuth
/// Credentials.
public struct OAuthSettings: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Domain hint to send as hd=? parameter in OAuth request flow. Enables
  /// redirect to primary IDP by skipping Google's login screen.
  /// https://developers.google.com/identity/protocols/OpenIDConnect#hd-param
  /// Note: IAP does not verify that the id token's hd claim matches this value
  /// since access behavior is managed by IAM policies.
  public var loginHint: GoogleWKT.WKTStringValue? = nil

  /// Optional. OAuth 2.0 client ID used in the OAuth flow.
  /// This allows for client sharing. The risks of client sharing
  /// are outlined here:
  /// https://cloud.google.com/iap/docs/sharing-oauth-clients#risks.
  public var clientId: GoogleWKT.WKTStringValue? = nil

  /// Optional. Input only. OAuth secret paired with client ID.
  public var clientSecret: GoogleWKT.WKTStringValue? = nil

  /// Output only. OAuth secret SHA256 paired with client ID.
  public var clientSecretSha256: GoogleWKT.WKTStringValue? = nil

  /// Optional. List of client ids allowed to use IAP programmatically.
  public var programmaticClients: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OAuthSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OAuthSettings().with { $0.loginHint = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let loginHint = CodingKeys(stringValue: "loginHint")
    static let clientId = CodingKeys(stringValue: "clientId")
    static let clientSecret = CodingKeys(stringValue: "clientSecret")
    static let clientSecretSha256 = CodingKeys(stringValue: "clientSecretSha256")
    static let programmaticClients = CodingKeys(stringValue: "programmaticClients")

    static let _knownKeys: Set<Swift.String> = [
      "loginHint",
      "clientId",
      "clientSecret",
      "clientSecretSha256",
      "programmaticClients",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.loginHint = try container.decodeIfPresent(
      GoogleWKT.WKTStringValue.self, forKey: .loginHint)
    self.clientId = try container.decodeIfPresent(GoogleWKT.WKTStringValue.self, forKey: .clientId)
    self.clientSecret = try container.decodeIfPresent(
      GoogleWKT.WKTStringValue.self, forKey: .clientSecret)
    self.clientSecretSha256 = try container.decodeIfPresent(
      GoogleWKT.WKTStringValue.self, forKey: .clientSecretSha256)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .programmaticClients)
    {
      self.programmaticClients = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.loginHint, forKey: .loginHint)
    try container.encodeIfPresent(self.clientId, forKey: .clientId)
    try container.encodeIfPresent(self.clientSecret, forKey: .clientSecret)
    try container.encodeIfPresent(self.clientSecretSha256, forKey: .clientSecretSha256)
    try container.encode(self.programmaticClients, forKey: .programmaticClients)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `OAuthSettings`: `"type.googleapis.com/google.cloud.iap.v1.OAuthSettings"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.iap.v1.OAuthSettings"
  }

  /// Initialize an instance of `OAuthSettings` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.iap.v1.OAuthSettings"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `OAuthSettings` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
