// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The OAuth 2.0 Settings
public struct OAuth2: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The OAuth 2.0 client ID registered in the workforce identity federation
  /// OAuth 2.0 Server.
  public var clientId: Swift.String = Swift.String()

  /// Input only. The OAuth 2.0 client secret created while registering the
  /// client ID.
  public var clientSecret: Swift.String = Swift.String()

  /// Output only. SHA256 hash value for the client secret. This field is
  /// returned by IAP when the settings are retrieved.
  public var clientSecretSha256: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OAuth2`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OAuth2().with { $0.clientId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let clientId = CodingKeys(stringValue: "clientId")
    static let clientSecret = CodingKeys(stringValue: "clientSecret")
    static let clientSecretSha256 = CodingKeys(stringValue: "clientSecretSha256")

    static let _knownKeys: Set<Swift.String> = [
      "clientId",
      "clientSecret",
      "clientSecretSha256",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clientId) {
      self.clientId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clientSecret) {
      self.clientSecret = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clientSecretSha256) {
      self.clientSecretSha256 = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.clientId, forKey: .clientId)
    try container.encode(self.clientSecret, forKey: .clientSecret)
    try container.encode(self.clientSecretSha256, forKey: .clientSecretSha256)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `OAuth2`: `"type.googleapis.com/google.cloud.iap.v1.OAuth2"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.iap.v1.OAuth2"
  }

  /// Initialize an instance of `OAuth2` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.iap.v1.OAuth2"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `OAuth2` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
