// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration for IAP reauthentication policies.
public struct ReauthSettings: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Reauth method requested.
  public var method: ReauthSettings.Method = ReauthSettings.Method()

  /// Optional. Reauth session lifetime, how long before a user has to
  /// reauthenticate again.
  public var maxAge: GoogleWKT.WKTDuration? = nil

  /// Optional. How IAP determines the effective policy in cases of hierarchical
  /// policies. Policies are merged from higher in the hierarchy to lower in the
  /// hierarchy.
  public var policyType: ReauthSettings.PolicyType = ReauthSettings.PolicyType()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ReauthSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReauthSettings().with { $0.method = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let method = CodingKeys(stringValue: "method")
    static let maxAge = CodingKeys(stringValue: "maxAge")
    static let policyType = CodingKeys(stringValue: "policyType")

    static let _knownKeys: Set<Swift.String> = [
      "method",
      "maxAge",
      "policyType",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(ReauthSettings.Method.self, forKey: .method) {
      self.method = value
    }
    self.maxAge = try container.decodeIfPresent(GoogleWKT.WKTDuration.self, forKey: .maxAge)
    if let value = try container.decodeIfPresent(
      ReauthSettings.PolicyType.self, forKey: .policyType)
    {
      self.policyType = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.method, forKey: .method)
    try container.encodeIfPresent(self.maxAge, forKey: .maxAge)
    try container.encode(self.policyType, forKey: .policyType)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Types of reauthentication methods supported by IAP.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Method: Codable, Equatable, Hashable, Sendable {
    /// Reauthentication disabled.
    case unspecified
    /// Prompts the user to log in again.
    case login
    @available(*, deprecated)
    case password
    /// User must use their secure key 2nd factor device.
    case secureKey
    /// User can use any enabled 2nd factor.
    case enrolledSecondFactors
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .login: return 1
      case .password: return 2
      case .secureKey: return 3
      case .enrolledSecondFactors: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "METHOD_UNSPECIFIED"
      case .login: return "LOGIN"
      case .password: return "PASSWORD"
      case .secureKey: return "SECURE_KEY"
      case .enrolledSecondFactors: return "ENROLLED_SECOND_FACTORS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Method/unknownStringValue(_:)).
    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "METHOD_UNSPECIFIED": self = .unspecified
      case "LOGIN": self = .login
      case "PASSWORD": self = .password
      case "SECURE_KEY": self = .secureKey
      case "ENROLLED_SECOND_FACTORS": self = .enrolledSecondFactors
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Method/unknownIntValue(_:)).
    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .login
      case 2: self = .password
      case 3: self = .secureKey
      case 4: self = .enrolledSecondFactors
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("METHOD_UNSPECIFIED")
      case .login: return try container.encode("LOGIN")
      case .password: return try container.encode("PASSWORD")
      case .secureKey: return try container.encode("SECURE_KEY")
      case .enrolledSecondFactors: return try container.encode("ENROLLED_SECOND_FACTORS")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Type of policy in the case of hierarchical policies.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum PolicyType: Codable, Equatable, Hashable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// This policy acts as a minimum to other policies, lower in the hierarchy.
    /// Effective policy may only be the same or stricter.
    case minimum
    /// This policy acts as a default if no other reauth policy is set.
    case `default`
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .minimum: return 1
      case .`default`: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "POLICY_TYPE_UNSPECIFIED"
      case .minimum: return "MINIMUM"
      case .`default`: return "DEFAULT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PolicyType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "POLICY_TYPE_UNSPECIFIED": self = .unspecified
      case "MINIMUM": self = .minimum
      case "DEFAULT": self = .`default`
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PolicyType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .minimum
      case 2: self = .`default`
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("POLICY_TYPE_UNSPECIFIED")
      case .minimum: return try container.encode("MINIMUM")
      case .`default`: return try container.encode("DEFAULT")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.iap.v1.ReauthSettings"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
